rules:
  - id: python-eval-usage
    patterns:
      - pattern: eval(...)
    message: Avoid eval() for security reasons
    languages: [python]
    severity: WARNING
  - id: python-exec-usage
    patterns:
      - pattern: exec(...)
    message: Avoid exec() for security reasons
    languages: [python]
    severity: WARNING
