# Generated by Django 5.2.14 on 2026-05-29 11:32

import django_pymissive.fields
import django_pymissive.models.attachment
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0007_alter_missive_missive_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missivebaseattachment',
            name='attachment_object_arguments',
            field=django_pymissive.fields.JSONField(blank=True, default=django_pymissive.models.attachment._default_attachment_object_arguments, help_text='Arguments to pass to the file method (as dict for **kwargs)', verbose_name='Attachment Object Arguments'),
        ),
    ]
