# Generated by Django 6.0.3 on 2026-05-30 16:01

import django.db.models.deletion
import django_pymissive.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_pymissive', '0008_alter_missivebaseattachment_attachment_object_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='missivescheduledcampaign',
            name='external_task_backend',
            field=models.CharField(blank=True, default='', help_text='Dotted path to a callable invoked with ``(scheduled_id)`` to run the campaign (e.g. "myapp.tasks.send_campaign"). The callable must be synchronous — it must complete all sending before returning, otherwise ended_at will be recorded prematurely. Ignored when task_object is configured. Must match settings.PYMISSIVE_ALLOWED_TASK_BACKENDS when set.', max_length=500, verbose_name='External task backend'),
        ),
        migrations.AddField(
            model_name='missivescheduledcampaign',
            name='missive_type',
            field=models.CharField(choices=[('*', 'All types'), ('lre', 'Electronic registered letter (LRE)'), ('hand_delivery', 'Hand delivery'), ('ere', 'Electronic registered email (ERE)'), ('email', 'Email'), ('email_marketing', 'Marketing email'), ('sms', 'SMS'), ('rcs', 'RCS (Rich SMS)'), ('voice_call', 'Automated voice call'), ('notification', 'In-app notification'), ('push_notification', 'Mobile push notification'), ('branded', 'Branded App messaging (WhatsApp, Slack, etc.)')], default='*', help_text="Restrict sending to missives of this type. '*' sends every type (default).", max_length=50, verbose_name='Missive type'),
        ),
        migrations.AddField(
            model_name='missivescheduledcampaign',
            name='task_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of the external object that handles task dispatch/execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Task object type'),
        ),
        migrations.AddField(
            model_name='missivescheduledcampaign',
            name='task_object_arguments',
            field=django_pymissive.fields.JSONField(blank=True, default=dict, help_text='Arguments for the external task object. Supported keys: "run_method" (method called on the task object, default "run_campaign"), "kwargs" (dict of extra keyword arguments forwarded to the method). The method must be synchronous — it must complete all sending before returning, otherwise ended_at will be recorded before any missive is sent.', verbose_name='Task object arguments'),
        ),
        migrations.AddField(
            model_name='missivescheduledcampaign',
            name='task_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the external task object.', null=True, verbose_name='Task object ID'),
        ),
        migrations.AlterField(
            model_name='missivecampaign',
            name='description',
            field=django_pymissive.fields.RichTextField(blank=True, default='', help_text='Campaign description (optional)', verbose_name='Description'),
        ),
    ]
