# Generated by Django 6.0.5 on 2026-05-31 13:31

import django.db.models.deletion
import django_pymissive.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_pymissive",
            "0009_missivescheduledcampaign_external_task_backend_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="missive",
            name="scheduler",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional scheduled campaign run that triggered this missive",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_missive",
                to="django_pymissive.missivescheduledcampaign",
                verbose_name="Scheduler",
            ),
        ),
        migrations.AddField(
            model_name="missivescheduledcampaign",
            name="retry_failed",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, missives that fail during this run are reset to DRAFT and retried once after the initial pass (history missives excluded).",
                verbose_name="Retry failed",
            ),
        ),
        migrations.AlterField(
            model_name="missivescheduledcampaign",
            name="external_task_backend",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Dotted path to a callable invoked with ``(scheduled_id)`` to run the campaign (e.g. "myapp.tasks.send_campaign"). Must match settings.PYMISSIVE_ALLOWED_TASK_BACKENDS when set.',
                max_length=500,
                verbose_name="External task backend",
            ),
        ),
        migrations.AlterField(
            model_name="missivescheduledcampaign",
            name="task_object_arguments",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=dict,
                help_text='Arguments for the external task object. Supported keys: "run_method" (method called on the task object, default "run_campaign"), "kwargs" (dict of extra keyword arguments forwarded to the method). The method must be synchronous.',
                verbose_name="Task object arguments",
            ),
        ),
    ]
