# Generated by Django 5.2.14 on 2026-05-31 16:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


def forwards_assign_uuids(apps, schema_editor):
    """Give every scheduled campaign a UUID and remap the missive FK to it.

    The original integer ``id`` values are mapped to freshly minted UUIDs and
    the link carried by ``Missive.scheduler`` is preserved through the temporary
    ``tmp_scheduler`` column.
    """
    Scheduler = apps.get_model("django_pymissive", "MissiveScheduledCampaign")
    Missive = apps.get_model("django_pymissive", "Missive")

    id_to_uuid = {
        old_id: uuid.uuid4()
        for old_id in Scheduler.objects.values_list("pk", flat=True)
    }
    for old_id, new_uuid in id_to_uuid.items():
        Scheduler.objects.filter(pk=old_id).update(tmp_uuid=new_uuid)

    missive_links = list(
        Missive.objects.filter(scheduler__isnull=False).values_list(
            "pk", "scheduler_id"
        )
    )
    for missive_pk, scheduler_id in missive_links:
        new_uuid = id_to_uuid.get(scheduler_id)
        if new_uuid is not None:
            Missive.objects.filter(pk=missive_pk).update(tmp_scheduler=new_uuid)


def swap_scheduler_pk_to_uuid(apps, schema_editor):
    """Swap the integer pk for the pre-populated UUID tmp_uuid column.

    On SQLite, Django 5.0/5.1 cannot atomically drop a pk column and rename
    another column to take its place: RemoveField on the pk implicitly
    re-introduces an ``id`` AutoField, so the subsequent RenameField fails with
    "duplicate column name: id". We work around this by doing the entire table
    reconstruction in a single explicit SQL sequence.

    On other databases (PostgreSQL, MySQL) standard DDL is used instead.
    """
    tbl = "django_pymissive_missivescheduledcampaign"
    vendor = schema_editor.connection.vendor

    if vendor == "sqlite":
        with schema_editor.connection.cursor() as cur:
            cur.execute(f"""
                CREATE TABLE "{tbl}__new" (
                    "id"                    char(32)     NOT NULL PRIMARY KEY,
                    "comment"               text         NULL,
                    "created_at"            datetime     NOT NULL,
                    "updated_at"            datetime     NOT NULL,
                    "scheduled_send_date"   datetime     NULL,
                    "send_date"             datetime     NULL,
                    "ended_at"              datetime     NULL,
                    "additional_config"     text         NOT NULL
                        CHECK ((JSON_VALID("additional_config") OR "additional_config" IS NULL)),
                    "campaign_id"           char(32)     NOT NULL
                        REFERENCES "django_pymissive_missivecampaign" ("id")
                        DEFERRABLE INITIALLY DEFERRED,
                    "external_task_backend" varchar(500) NOT NULL,
                    "missive_type"          varchar(50)  NOT NULL,
                    "task_content_type_id"  integer      NULL
                        REFERENCES "django_content_type" ("id")
                        DEFERRABLE INITIALLY DEFERRED,
                    "task_object_arguments" text         NOT NULL
                        CHECK ((JSON_VALID("task_object_arguments") OR "task_object_arguments" IS NULL)),
                    "task_object_id"        integer unsigned NULL
                        CHECK ("task_object_id" >= 0),
                    "retry_failed"          bool         NOT NULL
                )
            """)
            cur.execute(f"""
                INSERT INTO "{tbl}__new"
                    ("id", "comment", "created_at", "updated_at",
                     "scheduled_send_date", "send_date", "ended_at",
                     "additional_config", "campaign_id",
                     "external_task_backend", "missive_type",
                     "task_content_type_id", "task_object_arguments",
                     "task_object_id", "retry_failed")
                SELECT
                    "tmp_uuid", "comment", "created_at", "updated_at",
                    "scheduled_send_date", "send_date", "ended_at",
                    "additional_config", "campaign_id",
                    "external_task_backend", "missive_type",
                    "task_content_type_id", "task_object_arguments",
                    "task_object_id", "retry_failed"
                FROM "{tbl}"
            """)
            cur.execute(f'DROP TABLE "{tbl}"')
            cur.execute(f'ALTER TABLE "{tbl}__new" RENAME TO "{tbl}"')
            cur.execute(
                f'CREATE INDEX "django_pymissive_missivescheduledcampaign_campaign_id_5fff8da3"'
                f' ON "{tbl}" ("campaign_id")'
            )
            cur.execute(
                f'CREATE INDEX "django_pymissive_missivescheduledcampaign_task_content_type_id_015368e2"'
                f' ON "{tbl}" ("task_content_type_id")'
            )
    else:
        # PostgreSQL / MySQL: standard DDL — these databases handle pk column
        # removal and column rename without implicit pk re-injection.
        # CASCADE drops any FK constraints that reference the old integer id
        # (e.g. django_pymissive_missive.scheduler_id); they are recreated
        # later in this migration when the Missive.scheduler field is altered.
        with schema_editor.connection.cursor() as cur:
            cur.execute(f'ALTER TABLE "{tbl}" DROP COLUMN "id" CASCADE')
            cur.execute(f'ALTER TABLE "{tbl}" RENAME COLUMN "tmp_uuid" TO "id"')
            cur.execute(f'ALTER TABLE "{tbl}" ADD PRIMARY KEY ("id")')


def backwards_noop(apps, schema_editor):
    """Reversing the UUID conversion to integer ids is not supported."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0010_missive_scheduler_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missivescheduledcampaign',
            options={'ordering': ['-scheduled_send_date', '-ended_at', '-created_at'], 'verbose_name': 'Campaign send', 'verbose_name_plural': 'Campaign sends'},
        ),
        # 1. Temporary UUID columns holding the new identifiers and the remapped FK.
        migrations.AddField(
            model_name='missivescheduledcampaign',
            name='tmp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='missive',
            name='tmp_scheduler',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        # 2. Backfill: assign a UUID per scheduler and carry over the FK links.
        migrations.RunPython(forwards_assign_uuids, backwards_noop),
        # 3. Swap the scheduler pk: integer id → UUID (cross-version SQLite safe).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(swap_scheduler_pk_to_uuid, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='missivescheduledcampaign',
                    name='id',
                ),
                migrations.RenameField(
                    model_name='missivescheduledcampaign',
                    old_name='tmp_uuid',
                    new_name='id',
                ),
                migrations.AlterField(
                    model_name='missivescheduledcampaign',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
        # 4. Promote tmp_scheduler → scheduler FK on Missive.
        migrations.RemoveField(
            model_name='missive',
            name='scheduler',
        ),
        migrations.RenameField(
            model_name='missive',
            old_name='tmp_scheduler',
            new_name='scheduler',
        ),
        migrations.AlterField(
            model_name='missive',
            name='scheduler',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional scheduled campaign run that triggered this missive',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='to_missive',
                to='django_pymissive.missivescheduledcampaign',
                verbose_name='Scheduler',
            ),
        ),
    ]
