# Generated by Django 5.2.14 on 2026-05-31 16:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


def forwards_assign_uuids(apps, schema_editor):
    """Give every scheduled campaign a UUID and remap the missive FK to it.

    The original integer ``id`` values are mapped to freshly minted UUIDs and
    the link carried by ``Missive.scheduler`` is preserved through the temporary
    ``tmp_scheduler`` column.
    """
    Scheduler = apps.get_model("django_pymissive", "MissiveScheduledCampaign")
    Missive = apps.get_model("django_pymissive", "Missive")

    id_to_uuid = {
        old_id: uuid.uuid4()
        for old_id in Scheduler.objects.values_list("pk", flat=True)
    }
    for old_id, new_uuid in id_to_uuid.items():
        Scheduler.objects.filter(pk=old_id).update(tmp_uuid=new_uuid)

    missive_links = list(
        Missive.objects.filter(scheduler__isnull=False).values_list(
            "pk", "scheduler_id"
        )
    )
    for missive_pk, scheduler_id in missive_links:
        new_uuid = id_to_uuid.get(scheduler_id)
        if new_uuid is not None:
            Missive.objects.filter(pk=missive_pk).update(tmp_scheduler=new_uuid)


def backwards_noop(apps, schema_editor):
    """Reversing the UUID conversion to integer ids is not supported."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0010_missive_scheduler_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missivescheduledcampaign',
            options={'ordering': ['-scheduled_send_date', '-ended_at', '-created_at'], 'verbose_name': 'Campaign send', 'verbose_name_plural': 'Campaign sends'},
        ),
        # 1. Temporary UUID columns holding the new identifiers and the remapped FK.
        migrations.AddField(
            model_name='missivescheduledcampaign',
            name='tmp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='missive',
            name='tmp_scheduler',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        # 2. Backfill: assign a UUID per scheduler and carry over the FK links.
        migrations.RunPython(forwards_assign_uuids, backwards_noop),
        # 3. Drop the old integer FK and primary key.
        migrations.RemoveField(
            model_name='missive',
            name='scheduler',
        ),
        migrations.RemoveField(
            model_name='missivescheduledcampaign',
            name='id',
        ),
        # 4. Promote the UUID columns to be the primary key / FK.
        migrations.RenameField(
            model_name='missivescheduledcampaign',
            old_name='tmp_uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='missivescheduledcampaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='missive',
            old_name='tmp_scheduler',
            new_name='scheduler',
        ),
        migrations.AlterField(
            model_name='missive',
            name='scheduler',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional scheduled campaign run that triggered this missive',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='to_missive',
                to='django_pymissive.missivescheduledcampaign',
                verbose_name='Scheduler',
            ),
        ),
    ]
