# Generated by Django 5.2.15 on 2026-06-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_pymissive", "0012_rename_body_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missive",
            name="body_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text version of the message",
                null=True,
                verbose_name="Plain text body",
            ),
        ),
    ]
