# Generated by Django 5.2.15 on 2026-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0013_alter_missive_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiveevent',
            name='event',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('opened', 'Opened'), ('read', 'Read'), ('clicked', 'Clicked'), ('proofs_of_delivery', 'Proofs of Delivery'), ('untreated', 'Untreated'), ('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('processed', 'Processed'), ('deposit_proof', 'Deposit proof'), ('proof_of_content', 'Proof of content'), ('archived', 'Archived'), ('attempted_delivery', 'Attempted delivery'), ('prepare', 'Prepare'), ('pending', 'Pending'), ('processing', 'Processing'), ('queued', 'Queued'), ('proxy', 'Proxy'), ('request', 'Request'), ('deferred', 'Deferred'), ('scheduled', 'Scheduled'), ('unknown', 'Unknown'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('hard_bounce', 'Hard bounce'), ('soft_bounce', 'Soft bounce'), ('dropped', 'Dropped'), ('spam', 'Spam'), ('spam_report', 'Spam report'), ('blocked', 'Blocked'), ('rejected', 'Rejected'), ('refused', 'Refused'), ('invalid', 'Invalid'), ('carrier_rejected', 'Carrier rejected'), ('undelivered', 'Undelivered'), ('unsubscribe', 'Unsubscribe'), ('suppressed', 'Suppressed'), ('mailbox_full', 'Mailbox full'), ('domain_not_found', 'Domain not found'), ('error', 'Error')], help_text='Event type (sent, delivered, read, failed, etc.)', max_length=50, null=True, verbose_name='Event'),
        ),
    ]
